wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.10
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.8
    start_time: 1679052069.690212
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.8.8
      5: 0.13.10
      8:
      - 5
    visualize:
      mse vs crossentropy:
        panel_config:
          fieldSettings:
            lineKey: lineKey
            lineVal: lineVal
            step: step
          panelDefId: wandb/lineseries/v0
          stringSettings:
            title: mse vs cross_entropy
            xname: epochs
          transform:
            name: tableWithLeafColNames
          userQuery:
            queryFields:
            - args:
              - name: runSets
                value: ${runSets}
              fields:
              - fields: []
                name: id
              - fields: []
                name: name
              - fields: []
                name: _defaultColorIndex
              - args:
                - name: tableKey
                  value: mse vs crossentropy_table
                fields: []
                name: summaryTable
              name: runSets
        panel_type: Vega2
