program: train.py
method: bayes
name: "complete-sweep"
metric:
  name: val_accuracy
  goal: maximize
parameters:
    learning_rate:
      values: [0.001, 0.0001]
    optimizer:
      values: ["sgd", "momentum", "nag", "rmsprop", "adam", "nadam"]
    batch_size: 
      values: [128, 256, 512]
    epochs:
      values: [5, 10]
    weight_init:
      values: ["random", "xavier"]
    activation:
      values: ["sigmoid", "tanh", "relu"]
    weight_decay:
      values: [0, 0.0005]
    num_layers:
      values: [3, 4, 5]
    hidden_size:
      values: [32, 64]
    losses:
      values: ["cross_entropy", "mean_squared_error"]